import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  headerText: {
    color: "#0E96BD",
    textAlign: "right",
    marginTop: 5,
    marginRight: 20,
    fontSize: 15,
  },
  LeadText: { color: "black", fontSize: 18, marginLeft: 30, marginTop: 10 },
  header: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 20,
    paddingBottom: 50,
  },
  Facebook: {
    borderWidth: 1,
    borderColor: "#3B5998",
    alignItems: "center",
    justifyContent: "center",
    width: 150,
    height: 50,
    backgroundColor: "#3B5998",
    borderRadius: 50,
    marginRight: 70,
  },
  Google: {
    borderWidth: 1,
    borderColor: "#3B5998",
    alignItems: "center",
    justifyContent: "center",
    width: 150,
    height: 50,
    backgroundColor: "#fff",
    borderRadius: 50,
  },
  FacebookText: { color: "#fff", fontSize: 15, marginTop: -5 },
  GoogleText: { color: "#000000", fontSize: 15, marginTop: -5 },
  footer: {
    flex: 3,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  LastText: {
    color: "#666666",
    textAlign: "center",
    marginTop: 10,
  },
  SignInText: {
    color: "#fff",
    fontSize: 15,
    marginTop: -5,
    textAlign: "center",
  },
  SignInButton: {
    borderWidth: 1,
    borderColor: "#3B5998",
    alignItems: "center",
    justifyContent: "center",
    width: 150,
    height: 50,
    backgroundColor: "#1555F1",
    borderRadius: 50,
    marginTop: 10,
  },
  EmailText: {
    color: "#ABA6A3",
    fontSize: 20,
    marginTop: 20,
    marginLeft: 80,
  },
  dividerText: {
    textAlign: "center",
    fontSize: 15,
    marginTop: 20,
    color: "#ABA6A3",
  },
  text_header: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 30,
  },
  text_footer: {
    color: "#05375a",
    fontSize: 18,
  },
  action: {
    flexDirection: "row",
    marginTop: 0,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f2f2",
    paddingBottom: 5,
  },
  actionError: {
    flexDirection: "row",
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#FF0000",
    paddingBottom: 5,
  },
  textInput: {
    flex: 1,
    // marginTop: Platform.OS === "ios" ? 0 : -12,
    paddingLeft: 10,
    color: "#05375a",
  },
  errorMsg: {
    color: "#FF0000",
    fontSize: 14,
  },
  button: {
    alignItems: "center",
    marginTop: 50,
  },
  signIn: {
    width: "100%",
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  textSign: {
    fontSize: 18,
    fontWeight: "bold",
  },
});
